# Generated by Django 3.0.3 on 2020-02-05 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_info', models.CharField(max_length=30)),
                ('number', models.CharField(editable=False, max_length=16, unique=True)),
                ('balance', models.FloatField()),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField()),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('CANCELED', 'CANCELED'), ('ERROR', 'ERROR'), ('IN PROCESS', 'IN PROCESS')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ToOuterTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_to', models.CharField(max_length=26)),
                ('trans_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Account')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='InnerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_from', to='base.Account')),
                ('trans_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_to', to='base.Account')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='FromOuterTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_from', models.CharField(max_length=26)),
                ('trans_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Account')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=16, unique=True)),
                ('end_date', models.DateField(default=datetime.date(2021, 2, 4))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.User'),
        ),
    ]
